In [2]:
# IMPORT LIBRARIES
import mxnet
from mxnet import nd
print("MXNet version", mxnet.__version__) # Matteo 1.5.1

MXNet version 1.5.1


In [6]:
# CREATE AN NDARRAY (MXNET)
x = nd.array(((1,2,3),(5,6,7))) # CRETE AN ARRAY
# ACCESS DIMENSIONS
print(x.shape, x.size, x.dtype)
# INITIALIZAD WITH GAUSS(0,1)
y = nd.random.uniform(-1,1,(2,3))
x

(2, 3) 6 <class 'numpy.float32'>



[[1. 2. 3.]
 [5. 6. 7.]]
<NDArray 2x3 @cpu(0)>

In [19]:
# DOT-PRODUCT or ELEMENT WISE MULTIPLICATION FOLLOWED BY SUM
vector_x = nd.array((1,2,3))
vector_y = nd.array((4,5,6))
option_1 = nd.dot(vector_x, vector_y.T)
option_2 = nd.sum(vector_x * vector_y)
print(option_1, option_2)


[32.]
<NDArray 1 @cpu(0)> 
[32.]
<NDArray 1 @cpu(0)>


In [21]:
# COMPARE TWO ARRAY
nd.equal(option_1, option_2)
option_1 == option_2


[1.]
<NDArray 1 @cpu(0)>

In [22]:
# CONVERSION TO (CLASSICAL) NUMPY
a = x.asnumpy()
(type(a), a)

(numpy.ndarray, array([[1., 2., 3.],
        [5., 6., 7.]], dtype=float32))

In [24]:
# CREATE FIRST NEURAL NETWORK
from mxnet.gluon import nn

In [26]:
# CREATE MY FIRST LAYER
layer = nn.Dense(2) # 2 neurons FULLY-CONNECTED
layer

Dense(None -> 2, linear)

https://mxnet.incubator.apache.org/api/python/docs/api/gluon/nn/index.html#mxnet.gluon.nn.Dense

In [27]:
# INITIALIZE IT
layer.initialize()

In [28]:
# FEED SOME INPUT DATA (NO DIMENSION)
input_datapoint_for_single_layer = nd.random.uniform(-1,1,(3,4)) # input matrix 3x4 from UNIFORM(-1,1))
output_of_this_layer = layer(input_datapoint_for_single_layer)
output_of_this_layer


[[ 0.0009278  -0.00674768]
 [-0.02683341  0.00671751]
 [ 0.00798804  0.02131375]]
<NDArray 3x2 @cpu(0)>

NOTE: we didn’t specify the input size of layer before (though we can specify it with the argument in_units=4 here), <b>the system will automatically infer it during the first time we feed in data</b>, create and initialize the weights.

In [29]:
# NOW (AFTER FIRST PASS) WE CAN ACCESS WEIGHTS
layer.weight.data()


[[-0.01631819 -0.00312688  0.0408415   0.04370362]
 [ 0.00404529 -0.0028032   0.00952624 -0.01501013]]
<NDArray 2x4 @cpu(0)>

In [32]:
# START WITH DEEP LEARNING -> CREATE A DEEP LEARNING NETWORK
first_net = nn.Sequential()
# Add a sequence of layers.
first_net.add(# Similar to Dense, it is not necessary to specify the input channels
        # by the argument `in_channels`, which will be  automatically inferred
        # in the first forward pass. Also, we apply a relu activation on the
        # output. In addition, we can use a tuple to specify a  non-square
        # kernel size, such as `kernel_size=(2,4)`
        nn.Conv2D(channels=6, kernel_size=5, activation='relu'),
        # One can also use a tuple to specify non-symmetric pool and stride sizes
        nn.MaxPool2D(pool_size=2, strides=2),
        nn.Conv2D(channels=16, kernel_size=3, activation='relu'),
        nn.MaxPool2D(pool_size=2, strides=2),
        # The dense layer will automatically reshape the 4-D output of last
        # max pooling layer into the 2-D shape: (x.shape[0], x.size/x.shape[0])
        nn.Dense(120, activation="relu"),
        nn.Dense(84, activation="relu"),
        nn.Dense(10))
# INSPECT THE RESULT
first_net

Sequential(
  (0): Conv2D(None -> 6, kernel_size=(5, 5), stride=(1, 1), Activation(relu))
  (1): MaxPool2D(size=(2, 2), stride=(2, 2), padding=(0, 0), ceil_mode=False, global_pool=False, pool_type=max, layout=NCHW)
  (2): Conv2D(None -> 16, kernel_size=(3, 3), stride=(1, 1), Activation(relu))
  (3): MaxPool2D(size=(2, 2), stride=(2, 2), padding=(0, 0), ceil_mode=False, global_pool=False, pool_type=max, layout=NCHW)
  (4): Dense(None -> 120, Activation(relu))
  (5): Dense(None -> 84, Activation(relu))
  (6): Dense(None -> 10, linear)
)

In [33]:
# LET's USE our NETWORK -> PREPARE AN INPUT
first_net.initialize()
# Input shape is (batch_size, color_channels, height, width)
input_datapoint_for_NN = nd.random.uniform(shape=(4,1,28,28))
# uniformly sampled form GAUS(0,1)
print(input_datapoint_for_NN)


[[[[0.92559665 0.83607876 0.07103606 ... 0.5820198  0.14335328
    0.53737324]
   [0.9446689  0.7586156  0.5218483  ... 0.44994998 0.3595079
    0.61306345]
   [0.43703195 0.9023486  0.6976312  ... 0.93553907 0.53881675
    0.8463109 ]
   ...
   [0.8052232  0.01178803 0.52164716 ... 0.7137619  0.10873607
    0.51789856]
   [0.89390415 0.7853887  0.85715425 ... 0.86400425 0.08395315
    0.15514489]
   [0.71272594 0.77483064 0.5995434  ... 0.29543683 0.03342143
    0.08252441]]]


 [[[0.95694935 0.7259542  0.13720933 ... 0.56314117 0.0208098
    0.80126536]
   [0.13521017 0.94317764 0.11627302 ... 0.89298266 0.9657492
    0.17915347]
   [0.9726011  0.758584   0.45344925 ... 0.53057545 0.3475812
    0.9932467 ]
   ...
   [0.1671392  0.09982012 0.39244246 ... 0.39494097 0.28793445
    0.47957394]
   [0.8224663  0.39094034 0.62618303 ... 0.2944338  0.69951206
    0.05285462]
   [0.9998673  0.31748822 0.22006729 ... 0.7388402  0.24729377
    0.27477896]]]


 [[[0.6718066  0.48458487 0.56172

In [36]:
# FIRE! (FEED INPUT)
output_of_first_NN = first_net(input_datapoint_for_NN)
# THE OUTPUT WIL HAVE (batch_size, nr_output_layer_neurons)
output_of_first_NN.shape

(4, 10)

In [37]:
# ACCESS A PARTICULAR BIAS AND WEIGHT
(first_net[0].weight.data().shape, first_net[5].bias.data().shape)

((6, 1, 5, 5), (84,))

In [38]:
# PERSONALIzED LAYERS
class MixMLP(nn.Block):
    def __init__(self, **kwargs):
        # Run `nn.Block`'s init method
        super(MixMLP, self).__init__(**kwargs)
        # CERATE AN INTERNAL BLOCK (THAT IS AN ENTIRE NETWORK ITSELF)
        self.blk = nn.Sequential()
        self.blk.add(nn.Dense(3, activation='relu'),
                     nn.Dense(4, activation='relu'))
        self.dense = nn.Dense(5)
        
    def forward(self, x):
        y = nd.relu(self.blk(x))
        print(y) # PRINT INTERMEDIATE RESULT
        return self.dense(y)

personalized_net = MixMLP()
personalized_net

MixMLP(
  (blk): Sequential(
    (0): Dense(None -> 3, Activation(relu))
    (1): Dense(None -> 4, Activation(relu))
  )
  (dense): Dense(None -> 5, linear)
)

https://mxnet.apache.org/api/python/docs/tutorials/getting-started/crash-course/2-nn.html

In [39]:
personalized_net.initialize()
input_dataoint_for_personalized_net = nd.random.uniform(shape=(2,2))
personalized_net(input_dataoint_for_personalized_net)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 2x4 @cpu(0)>



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<NDArray 2x5 @cpu(0)>

In [41]:
personalized_net.blk[1].weight.data()


[[-0.02634858  0.05334064  0.02748809]
 [ 0.06669661 -0.01711474  0.01647211]
 [-0.04485548  0.00594983 -0.06654498]
 [ 0.04964591 -0.06058505  0.03413684]]
<NDArray 4x3 @cpu(0)>